# Generated by Django 6.0 on 2025-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('present', 'Пришёл'), ('absent', 'Не пришёл'), ('none', 'Не отмечен')], max_length=10),
        ),
    ]
